### ISSUE TITLE
UI 작업

### ISSUE THREAD

**Issue by inae-dev** [inae-dev/MC-AudioPlayer-Task#1]
## 📌 TODO
- [x] 테이블 뷰 띄우기
- [x] 음악 셀 생성 및 레이아웃 잡기
- [x] 하단 재생바 커스텀 뷰
- [x] 하단 재생바 버튼 구성
- [ ] 음악 상세 뷰 구성 ...
- [x] 셀 터치 시 하단 재생바 노출

**Comment by inae-dev** [comment]
## Issue
+ **MusicTableViewCell** 
uiview-encapsulated-layout-height constraints 충돌.. 
-> `separatorStyle = .none`로 일단은 로그 안 뜨게 함..
대체 왜?

**Comment by inae-dev** [comment]
> ## Issue
> * **MusicTableViewCell**
>   uiview-encapsulated-layout-height constraints 충돌..
>   -> `separatorStyle = .none`로 일단은 로그 안 뜨게 함..
>   대체 왜?

cell에 잡힌 top, bottom layout priority 조정해서 해결함!
