### ISSUE TITLE
네트워크 통신

### ISSUE THREAD

**Issue by inae-dev** [inae-dev/MC-AudioPlayer-Task#2]
## 📌 TODO
- [x] 서버 통신 환경 셋팅

> 

- [x] static URL 통신 후 저장
- [x] list.json 데이터 뿌리기

> 

- [x] 이미지 처리 (라이브러리 쓸지 말지 .. )
