### ISSUE TITLE
하단 재생바 기능 구현

### ISSUE THREAD

**Issue by inae-dev** [inae-dev/MC-AudioPlayer-Task#3]
## 📌 TODO
- [ ] ~~pan gesture로 제스처 감지 (사용 예정..)~~ (#6 에서 진행함)
- [x] 버튼 좌, 우 넘김 기능 구현 
- [ ] 일시정지 기능 구현
- [ ] progress bar 기능
- [ ] 15초 skip 기능 구현
